### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by astratow** [elizabethrsotomayor/wikiclone#1]
Hi Elisabeth,
Long time no speak!
Would you be able to load page to netlify  or similar service so we can view it? Many thanks!
Artur

**Comment by elizabethrsotomayor** [comment]
Hi Artur,
It's good to hear from you! I have deployed the site to [GitHub pages](https://elizabethrsotomayor.github.io/wikiclone/) since it's written in basic HTML/CSS. It's just a small first project for a bootcamp I'll be attending through August. Thanks for looking! Hope everything is going good in your hello world! Take care.
Elizabeth
